#!/usr/bin/env python3
"""
build_fig_scope.py
Regenerates fig_scope.pdf (paper §VIII, \\label{fig:scope})
as a clean VECTOR PDF, fully self-contained.

What the figure shows
---------------------
(a) bib--bib at the uniform-Nash fixed point: the heavy tail lives ONLY in the
    internal argmax-persistence (truncated power law, alpha ~ 1.45, consistent
    with the universal 1.43 +/- 0.02); every behavioural streak statistic
    (hand-repeat runs, win streaks) is exponential. Internal-state criticality
    is masked behaviourally because cyclic-dominance adversarial pinning clamps
    the action marginal to uniform Nash.

(b) The same behavioural observable (hand-repeat runs) once the adversarial
    pinning is removed: against a FIXED biased opponent (0.6,0.2,0.2) the bib
    agent locks onto an exploiting hypothesis, P(d|h*) concentrates, and the
    hand-run tail turns from exponential into a power law (alpha ~ 1.25) --
    behavioural Levy re-appears. Hand frequency becomes strongly biased
    (~0.21/0.63/0.16) where it is uniform when pinned.

Why this script exists / what changed
-------------------------------------
The previous plotting script (experiments/tie_vs_smoothing/plot_internal_vs_behavior.py)
imported the simulation engine (engine_tie_smoothing) only for its
fit_distributions() helper. To match the other paper figure-build scripts in
this directory, the AIC model selection (power-law / truncated-power-law /
exponential) is inlined here so the figure rebuilds from bundled data with
nothing but numpy / matplotlib / powerlaw.

Data source (bundled, self-contained):
    figures/scripts/data/data_ivb_equil.npz   (bib-bib at uniform Nash)
    figures/scripts/data/data_ivb_biased.npz  (bib vs fixed biased opponent)
arrays in each: argmax_persist, hand_runs, win_streaks, hand_freq, T, n_runs, astart
(generated by experiments/tie_vs_smoothing/gen_internal_vs_behavior.py)

Output: ../fig_scope.pdf (and .png preview)
"""
import os
import sys
import warnings
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import powerlaw

warnings.filterwarnings("ignore")

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import figdata
FIG_DIR = str(figdata.FIG_DIR)
DATA = str(figdata.BUNDLED)          # figures/scripts/data (bundled inputs)

OUT_PDF = os.path.join(FIG_DIR, "fig_scope.pdf")
OUT_PNG = os.path.join(FIG_DIR, "fig_scope.png")

plt.rcParams.update({
    "font.size": 11, "font.family": "sans-serif", "axes.linewidth": 0.8,
    "savefig.bbox": "tight", "savefig.dpi": 300,
    "pdf.fonttype": 42, "ps.fonttype": 42,
})


def panel_label(ax, letter):
    ax.text(-0.17, 1.04, letter.upper(), transform=ax.transAxes,
            fontsize=11, fontweight="bold", va="bottom", ha="left")


def fit_best(data, discrete=True):
    """AIC model selection over power-law / truncated-power-law / exponential.

    Inlined copy of engine_tie_smoothing.fit_distributions (same powerlaw.Fit
    auto-xmin and AIC-weight comparison), returning (best_name, alpha_best).
    """
    data = np.asarray(data)
    data = data[data >= 1]
    if len(data) < 30 or len(np.unique(data)) < 5:
        return "err", float("nan")
    fit = powerlaw.Fit(data, discrete=discrete, verbose=False)
    data_fit = data[data >= fit.xmin]
    if len(data_fit) < 10:
        return "err", float("nan")

    def _ll(dist):
        if dist is None:
            return None
        try:
            p = np.asarray(dist.pdf(data_fit), dtype=float)
            p = np.where(p > 0, p, 1e-300)
            return float(np.sum(np.log(p)))
        except Exception:
            return None

    try:
        pl_dist = fit.power_law
    except Exception:
        pl_dist = None
    try:
        tpl_dist = fit.truncated_power_law
    except Exception:
        tpl_dist = None
    try:
        exp_dist = fit.exponential
    except Exception:
        exp_dist = None

    available = {}
    for name, d in (("pl", pl_dist), ("tpl", tpl_dist), ("exp", exp_dist)):
        ll = _ll(d)
        if ll is not None:
            available[name] = ll
    if not available:
        return "err", float("nan")

    n_params = {"pl": 1, "exp": 1, "tpl": 2}
    aic = {k: 2 * n_params[k] - 2 * ll for k, ll in available.items()}
    aic_min = min(aic.values())
    raw = {k: np.exp(-(v - aic_min) / 2) for k, v in aic.items()}
    total = sum(raw.values())
    weights = {k: v / total for k, v in raw.items()}
    for k in ("pl", "tpl", "exp"):
        weights.setdefault(k, 0.0)
    best = max(weights, key=weights.get)

    alpha_pl = float(pl_dist.alpha) if pl_dist is not None else np.nan
    alpha_tpl = float(tpl_dist.alpha) if tpl_dist is not None else np.nan
    if best == "pl" and not np.isnan(alpha_pl):
        alpha_best = alpha_pl
    elif best == "tpl" and not np.isnan(alpha_tpl):
        alpha_best = alpha_tpl
    elif not np.isnan(alpha_tpl):
        alpha_best = alpha_tpl
    elif not np.isnan(alpha_pl):
        alpha_best = alpha_pl
    else:
        alpha_best = np.nan
    return best, float(alpha_best)


def ccdf(data, xmin=1):
    d = np.sort(np.asarray(data, float))
    d = d[d >= xmin]
    n = d.size
    x = np.unique(d)
    cc = 1.0 - (np.searchsorted(d, x, side="left")) / n
    return x, cc


def plot_ccdf(ax, data, color, marker, label):
    x, cc = ccdf(data)
    ax.loglog(x, cc, marker=marker, ls="none", ms=3.2, mfc="none",
              mec=color, alpha=0.8, label=label)
    return x, cc


def overlay_tpl_fit(ax, data, color):
    """Overlay the fitted truncated-power-law CCDF as a curve that follows the
    cutoff. Uses the SAME fit (powerlaw auto-selected xmin), anchored to the
    empirical CCDF at xmin. Returns (alpha, xmin)."""
    d = np.asarray(data, float)
    d = d[d >= 1]
    n_total = d.size
    fit = powerlaw.Fit(d, discrete=True, verbose=False)   # auto xmin
    tpl = fit.truncated_power_law
    alpha = float(tpl.alpha)
    lam = float(getattr(tpl, "Lambda", getattr(tpl, "parameter2", 0.0)))
    xmin = int(round(fit.xmin))
    xmax = int(d.max())
    kk = np.arange(xmin, xmax + 1, dtype=float)
    w = kk ** (-alpha) * np.exp(-lam * kk)
    w /= w.sum()
    surv = np.cumsum(w[::-1])[::-1]                 # P(X>=k | X>=xmin), =1 at xmin
    cc_at_xmin = (d >= xmin).sum() / n_total        # empirical CCDF at xmin
    ax.loglog(kk, surv * cc_at_xmin, "--", color=color, lw=1.5,
              alpha=0.95, zorder=5)
    return alpha, xmin


equil = np.load(os.path.join(DATA, "data_ivb_equil.npz"))
biased = np.load(os.path.join(DATA, "data_ivb_biased.npz"))

plt.rcParams.update({"font.family":"sans-serif","font.sans-serif":["Helvetica","Arial","DejaVu Sans"],"font.size":8,"axes.labelsize":8.5,"xtick.labelsize":7.5,"ytick.labelsize":7.5,"legend.fontsize":6,"axes.linewidth":0.8,"lines.linewidth":1.0,"xtick.direction":"in","ytick.direction":"in","xtick.major.size":3,"ytick.major.size":3,"xtick.minor.size":1.8,"ytick.minor.size":1.8,"axes.spines.top":False,"axes.spines.right":False,"pdf.fonttype":42,"ps.fonttype":42})  # PNAS-unified
fig, (axA, axB) = plt.subplots(1, 2, figsize=(7.0, 3.05))

# ---- (a) equilibrium: internal vs behavioural ----
b_am, a_am = fit_best(equil["argmax_persist"])
b_hr, a_hr = fit_best(equil["hand_runs"])
b_ws, a_ws = fit_best(equil["win_streaks"])
plot_ccdf(axA, equil["argmax_persist"], "#b2182b", "o",
          r"internal: argmax")
al_a, _ = overlay_tpl_fit(axA, equil["argmax_persist"], "#b2182b")
axA.plot([], [], "--", color="#b2182b", lw=1.4,
         label=rf"TPL fit ($\alpha$={al_a:.2f})")
plot_ccdf(axA, equil["hand_runs"], "#2166ac", "s",
          r"hand-repeat (exp.)")
plot_ccdf(axA, equil["win_streaks"], "#4d9221", "^",
          r"win streaks (exp.)")
axA.set_xlabel("run length")
axA.set_ylabel(r"CCDF  $P(X \geq x)$")
axA.legend(fontsize=6.5, loc="upper right", frameon=False)
axA.set_ylim(1e-5, 1.5)
panel_label(axA, "a")

# ---- (b) loosening: hand-runs exponential -> power law vs fixed biased ----
plot_ccdf(axB, equil["hand_runs"], "#2166ac", "s",
          r"bib--bib (pinned, exp.)")
b_hrb, a_hrb = fit_best(biased["hand_runs"])
plot_ccdf(axB, biased["hand_runs"], "#ee7733", "o",
          r"vs fixed-biased opp.")
al_b, _ = overlay_tpl_fit(axB, biased["hand_runs"], "#ee7733")
axB.plot([], [], "--", color="#ee7733", lw=1.4,
         label=rf"TPL fit ($\alpha$={al_b:.2f})")
hf = biased["hand_freq"]
axB.set_xlabel("hand-repeat run length")
axB.set_ylabel(r"CCDF  $P(X \geq x)$")
axB.legend(fontsize=6.5, loc="upper right", frameon=False)
axB.set_ylim(1e-5, 1.5)
axB.text(0.04, 0.04,
         f"hand bias r/p/s\n= {hf[0]:.2f}/{hf[1]:.2f}/{hf[2]:.2f}\n(uniform when pinned)",
         transform=axB.transAxes, ha="left", va="bottom", fontsize=6.5,
         bbox=dict(boxstyle="round,pad=0.25", fc="white", ec="0.6"))
panel_label(axB, "b")

fig.subplots_adjust(wspace=0.22)
fig.tight_layout()
fig.savefig(OUT_PDF)
fig.savefig(OUT_PNG, dpi=200)
print("panel (a) equil:  argmax", b_am, round(a_am, 2),
      "| hand_runs", b_hr, "| win", b_ws)
print("panel (b) biased: hand_runs", b_hrb, round(a_hrb, 2),
      "| hand bias", np.round(hf, 3))
print("wrote:", OUT_PDF)
print("wrote:", OUT_PNG)
